name: Version or Publish

on:
  push:
    branches:
      - master
      
jobs:
  changeset:
    name: Changeset
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn
        working-directory: ./mobile

      - name: Generate changeset
        run: changeset-version
  