name: Version or Publish

on:
  push:
    branches:
      - master
      
jobs:
  changeset:
    name: Changeset
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn
        working-directory: ./mobile

      - name: Generate changeset
        run: changeset-version

  update_master:
    - name: Commit changelog
      run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: update changeset"
          git push origin ${{ github.ref_name }}
          echo "All done"
  