name: Version or Publish

on:
  push:
    branches:
      - master
      
jobs:
  changeset:
    name: Changeset
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Generate changeset
        run: yarn changeset-version

      - name: Atualizando github  
        env: 
          BRANCH: ${{ github.ref_name }}
        run: |
          echo "Branch is ... ${BRANCH}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: update changelog"
          git push origin $BRANCH

  create-pull-request:
    name: Atualizando Dev
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: 'Update Develop Branch',
              owner: 'github-actions[bot]',
              repo,
              head: 'master',
              base: 'develop',
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['feature', 'automated pr']
            });